version: '2'

services:
  basicstation:
    build: ./basicstation
    privileged: true
    tty: true
    restart: always
    network_mode: host
    volumes:
      - 'resin-data:/data'
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
  wifi-connect:
    build: ./wifi-connect
    network_mode: host
    restart: always
    labels:
        io.balena.features.dbus: '1'
    cap_add:
        - NET_ADMIN
    environment:
        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  serial:
    build: ./serial-bridge
    privileged: true
    tty: true
    restart: always
    network_mode: host
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
  node-exporter:
    build: ./node-exporter
    privileged: true
    tty: true
    network_mode: host
    restart: always
    command: --collector.wifi
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
      io.balena.features.dbus: '1'
  scheduler:
    build: ./scheduler
    restart: always
    network_mode: host

networks: {}

volumes:
  resin-data: {}
